# Generated by Django 4.0.4 on 2022-05-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='matricula',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
