# Generated by Django 4.0.4 on 2022-06-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_agendamentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamentos',
            name='data',
            field=models.CharField(max_length=50),
        ),
    ]
