# Generated by Django 4.0.4 on 2022-06-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_alter_usuario_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
