# Generated by Django 4.0.4 on 2022-06-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_alter_agendamentos_accepted_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamentos',
            name='categoria',
            field=models.BooleanField(default=False),
        ),
    ]
