# Generated by Django 4.0.4 on 2022-06-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_usuario_bio_usuario_curso_usuario_periodo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
