# Generated by Django 4.0.4 on 2022-06-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_alter_agendamentos_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamentos',
            name='categoria',
            field=models.BooleanField(default=True),
        ),
    ]
