# Generated by Django 4.0.4 on 2022-06-05 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0008_alter_agendamentos_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamentos',
            old_name='nome',
            new_name='name',
        ),
    ]
