# Generated by Django 4.0.4 on 2022-06-05 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0009_rename_nome_agendamentos_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agendamentos',
            new_name='Consultas',
        ),
    ]
