# Generated by Django 4.0.4 on 2022-06-16 13:17

from django.db import migrations
import schedules.models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0015_alter_usuario_options_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', schedules.models.UserManager()),
            ],
        ),
    ]
